students = read.csv("E:/data analytics/datasets/students.csv",TRUE)
class(students)
dim(students)
names(students)
str(students)
head(students,10)
tail(students)
summary(students)
summary(students[,"Height"])
summary(students$Height)
